<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Detail Report</title>
    <!-- Load Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        /* Custom font for a more professional look */
        body { font-family: 'Inter', sans-serif; }
    </style>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        'primary': '#4f46e5',
                        'secondary': '#6366f1',
                    },
                }
            }
        }

        // Mock data to replace PHP variables for previewing
        const customer = {
            name: "Alexandra Dubois",
            email: "alexandra.dubois@example.com",
            phone: "+1 (555) 123-4567",
            status: "Active Lead",
            potential_revenue: 155000,
            currency: "USD",
            description: "High-priority account requiring customized software integration for their new Q4 project. Follow up by EOD Friday.",
        };

        // Function to format the currency
        function formatRevenue(amount, currency) {
            return `${currency} ${amount.toLocaleString('en-US', { minimumFractionDigits: 0 })}`;
        }

        document.addEventListener('DOMContentLoaded', () => {
            document.getElementById('customer-name').textContent = customer.name;
            document.getElementById('customer-email').textContent = customer.email || '-';
            document.getElementById('customer-phone').textContent = customer.phone || '-';
            document.getElementById('customer-status').textContent = customer.status;
            document.getElementById('customer-revenue').textContent = formatRevenue(customer.potential_revenue, customer.currency);
            document.getElementById('customer-description').textContent = customer.description || '-';
        });
    </script>
</head>
<body class="bg-gray-100 min-h-screen p-4 sm:p-8">

    <div class="max-w-4xl mx-auto mt-10 bg-white shadow-xl rounded-xl overflow-hidden">
        
        <!-- Header -->
        <div class="bg-primary p-6">
            <h1 class="text-2xl font-extrabold text-white text-center">Customer Detail Report</h1>
        </div>

        <!-- Detail Card -->
        <div class="p-6 sm:p-10">
            <h2 id="customer-name" class="text-3xl font-bold text-gray-800 mb-6 border-b pb-2"></h2>

            <div class="space-y-6">
                
                <!-- Detail Grid -->
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

                    <!-- Email -->
                    <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                        <p class="text-sm font-medium text-gray-500">Email</p>
                        <p id="customer-email" class="text-lg font-semibold text-gray-900 truncate"></p>
                    </div>

                    <!-- Phone -->
                    <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                        <p class="text-sm font-medium text-gray-500">Phone</p>
                        <p id="customer-phone" class="text-lg font-semibold text-gray-900"></p>
                    </div>
                    
                    <!-- Status -->
                    <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                        <p class="text-sm font-medium text-gray-500">Status</p>
                        <p id="customer-status" class="text-lg font-semibold text-green-600"></p>
                    </div>
                    
                    <!-- Potential Revenue -->
                    <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                        <p class="text-sm font-medium text-gray-500">Potential Revenue</p>
                        <p id="customer-revenue" class="text-xl font-extrabold text-primary"></p>
                    </div>
                </div>

                <!-- Description (Full Width) -->
                <div class="border border-gray-300 rounded-lg p-6 bg-white shadow-sm">
                    <p class="text-md font-semibold text-gray-700 mb-2 border-b pb-2">Description</p>
                    <p id="customer-description" class="text-gray-600 leading-relaxed italic"></p>
                </div>

            </div>
        </div>

        <!-- Footer for context -->
        <div class="bg-gray-50 p-4 text-center text-sm text-gray-400">
            Report generated by CRM System
        </div>

    </div>

</body>
</html>
